### ISSUE TITLE
Doesnt work on x86 emulator

### ISSUE THREAD

**Issue by Rockvole** [seamusv/event_channel_sample#1]
I tried your example on a Nexus 6 API 22 x86 emulator but it wont install with error :

    Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]
    Error launching application on Android SDK built for x86.

**Comment by seamusv** [comment]
This appears to be a known issue with some possible work arounds.

https://github.com/flutter/flutter/issues/8824

**Comment by seamusv** [comment]
Code has been updated to work with Flutter v1.1.4 and it now works in an x86 emulator.
